name: Build & Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, Linux, X64, local-minikube]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "service=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE="one290/shadowchats:${{ steps.get_version.outputs.service }}-v${{ steps.get_version.outputs.version }}"
          echo "Building image $IMAGE"
          docker build -t $IMAGE ./ 

      - name: Push Docker image
        run: |
          IMAGE="one290/shadowchats:${{ steps.get_version.outputs.service }}-v${{ steps.get_version.outputs.version }}"
          echo "Pushing image $IMAGE"
          docker push $IMAGE

      - name: Increment version
        run: |
          OLD_VERSION=$(cat VERSION)
          # Простейший патч-бамп
          IFS='.' read -r MAJ MIN PATCH <<< "$OLD_VERSION"
          PATCH=$((PATCH+1))
          echo "$MAJ.$MIN.$PATCH" > VERSION
          git config --local user.email "ci@example.com"
          git config --local user.name "CI Bot"
          git add VERSION
          git commit -m "Bump version to $MAJ.$MIN.$PATCH"
          git push
